### PR TITLE
Extend throwable in Exception marker interface

### PR DESCRIPTION
**Pull request by BackEndTea**

### CODE REVIEW

**Comment by Majkl578** [comment]
Tricky.
One one hand this is ok as Exceptions already implement all methods from Throwable.
On the other if anyone implemented _only_ this interface, it's a BC break.

@Ocramius Thoughts?

**Comment by Ocramius** [comment]
@Majkl578 not a BC break IMO, since implementing this interface not on an exception would be extremely unwise and already unsupported by us anyway, since the interface explicitly states:

```php
  * Base exception marker interface for the instantiator component 
```

Yes, we don't have a BC policy for this, but we can't have a BC policy for everything.

**Comment by Majkl578** [comment]
I basically quoted the reason why Symfony reverted this change, but I'm generally 👍 for these. Also plays well with https://github.com/phpstan/phpstan/pull/1001.

**Comment by BackEndTea** [comment]
Thanks for the review and merge @Ocramius & @Majkl578

**Comment by alcaeus** [comment]
Strictly speaking, this is a BC break: we're adding new methods to an interface that previously weren't there. I don't think this should be included in 1.x.

**Comment by malarzm** [comment]
But you need those method anyway :)

**Comment by Majkl578** [comment]
Technically you don't, I'd you mocked only the marker interface, you are now required to implement these new methods while there were none previously.

**Pull request merged**
