### PR TITLE
Modify http ocramius.github.com => https ocramius.github.io

### PR DESCRIPTION
**Pull request by matks**
Not sure it's worth it but well I noticed it so might as well report it 😄 

https://ocramius.github.io/ is secure
https://ocramius.github.com/ is not

### CODE REVIEW

**Review by greg0ire — APPROVED** [review]

**Comment by matks** [comment]
CI fails because Travis now runs Composer v2 and this collides with this project constraints.

This Monday, a lot of people have to fix their CI pipeline thanks to the release of Composer this weekend 😅

**Comment by matks** [comment]
I will rebase my PR when branch `1.3.x` passes CI 😉

**Comment by greg0ire** [comment]
See #76

**Comment by matks** [comment]
Thanks for merging ! 🎉

**Pull request merged**
